import localFont from "next/font/local";
import Navbar from "./components/nav/Nav";

export const metadata = {
  title: "Newbie Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
