import localFont from "next/font/local";
import Navbar from "./components/nav/Nav";
import { AuthProvider } from "./Providers";

export const metadata = {
  title: "Newbie Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
